### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:8080/api/alerts/engineer/1


###
POST http://localhost:8080/api/pagerduty/test

###
GET http://localhost:8080/api/pagerduty/incidents

###
GET http://localhost:8080/api/pagerduty/users

###
POST http://localhost:8080/api/pagerduty/sync

###
POST http://localhost:8080/api/pagerduty/resolve/Q1OR352S07LS07?email=prithvi@mlrit.ac.in





