POST http://localhost:8080/api/import
Content-Type: application/json

[
  {
    "pagerDutyIncidentId": "INC0001",
    "incidentNumber": 1,
    "title": "Database Failure",
    "status": "resolved",
    "triggeredAt": "2016-03-01T08:21:00",
    "resolvedAt": "2016-03-01T09:21:00",
    "severity": "P1",
    "serviceName": "Payments",
    "pagerDutyUserId": "PEA88GO",
    "assignedEngineerName": "Biradar Srikanth",
    "source": "API"
  }
]