
#Database configuration for Azure PostgreSQL

spring.datasource.url=${AZURE_DB_URL}
spring.datasource.username=${AZURE_DB_USERNAME}
spring.datasource.password=${AZURE_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#PagerDuty API configuration
pagerduty.base-url=https://api.pagerduty.com
pagerduty.integration-key=${PAGERDUTY_INTEGRATION_KEY}
pagerduty.api-token=${PAGERDUTY_API_TOKEN}
