# App
spring.application.name=Fairness-Checker
server.port=8080

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# PagerDuty
pagerduty.base-url=${PAGERDUTY_BASE_URL}
pagerduty.integration-key=${PAGERDUTY_INTEGRATION_KEY}
pagerduty.api-token=${PAGERDUTY_API_TOKEN}
pagerduty.webhook.secret=${PAGERDUTY_WEBHOOK_SECRET}

#Sync Timers
pagerduty.sync-rate=3000000


