
#App
spring.application.name=Fairness-Checker
server.port=${PORT:8080}

#FastAPI App
python_scorer_base_url=http://127.0.0.1:8000

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Azure PostgreSQL
spring.datasource.url=${AZURE_DB_URL}
spring.datasource.username=${AZURE_DB_USERNAME}
spring.datasource.password=${AZURE_DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

# PagerDuty
pagerduty.base-url=${PAGERDUTY_BASE_URL}
pagerduty.integration-key=${PAGERDUTY_INTEGRATION_KEY}
pagerduty.api-token=${PAGERDUTY_API_TOKEN}
pagerduty.webhook.secret=${PAGERDUTY_WEBHOOK_SECRET}

#Sync Timers
pagerduty.sync-rate=3000000




