-- Baseline: the schema Hibernate created before Flyway was introduced.
-- Existing databases are baselined at version 1 (spring.flyway.baseline-on-migrate) and skip this file;
-- new databases (CI, local, fresh environments) run it.

CREATE TABLE engineer_data (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email              VARCHAR(255) NOT NULL,
    name               VARCHAR(255) NOT NULL,
    pager_duty_user_id VARCHAR(255) UNIQUE,
    team               VARCHAR(255) NOT NULL
);

CREATE TABLE alert_event (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assigned_engineer_name VARCHAR(255),
    incident_number        INTEGER,
    pager_duty_incident_id VARCHAR(255),
    pager_duty_user_id     VARCHAR(255),
    resolved_at            TIMESTAMP(6),
    service_id             VARCHAR(255),
    service_name           VARCHAR(255),
    severity               VARCHAR(255),
    source                 VARCHAR(255),
    status                 VARCHAR(255),
    title                  VARCHAR(255),
    triggered_at           TIMESTAMP(6) NOT NULL,
    urgency                VARCHAR(255),
    engineer_id            BIGINT REFERENCES engineer_data (id)
);
