-- Normalises teams and services, adds paging history and on-call shifts, richer alert data and
-- database-enforced integrity. Existing data was checked against every constraint before this was written.

-- ---------------------------------------------------------------------------------------------------------
-- Audit columns: filled by the database, so every writer (app, psql, scripts) gets them
-- ---------------------------------------------------------------------------------------------------------
CREATE FUNCTION set_updated_at() RETURNS trigger
    LANGUAGE plpgsql AS
$$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END
$$;

-- ---------------------------------------------------------------------------------------------------------
-- team: was a free-text column on engineer_data
-- ---------------------------------------------------------------------------------------------------------
CREATE TABLE team (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    -- IANA name; decides what counts as night/weekend for this team's engineers
    timezone   VARCHAR(64)  NOT NULL DEFAULT 'Asia/Kolkata',
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_team_name UNIQUE (name)
);

INSERT INTO team (name)
SELECT DISTINCT team FROM engineer_data;

ALTER TABLE engineer_data
    ADD COLUMN team_id    BIGINT,
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

UPDATE engineer_data e
SET team_id = t.id
FROM team t
WHERE t.name = e.team;

ALTER TABLE engineer_data
    ALTER COLUMN team_id SET NOT NULL,
    ADD CONSTRAINT fk_engineer_team FOREIGN KEY (team_id) REFERENCES team (id);

CREATE INDEX ix_engineer_team_id ON engineer_data (team_id);
CREATE UNIQUE INDEX ux_engineer_email ON engineer_data (lower(email));

-- The scorer view read engineer_data.team; point it at the team table before dropping the column.
-- Existing columns keep their names and types; team_id and timezone are appended.
CREATE OR REPLACE VIEW scoring_engineer_v AS
SELECT e.id AS engineer_id, e.name, t.name AS team, e.active, t.id AS team_id, t.timezone
FROM engineer_data e
         JOIN team t ON t.id = e.team_id;

ALTER TABLE engineer_data DROP COLUMN team;

-- ---------------------------------------------------------------------------------------------------------
-- service: was two free-text columns on alert_event
-- ---------------------------------------------------------------------------------------------------------
CREATE TABLE service (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pagerduty_service_id VARCHAR(255),
    name                 VARCHAR(255) NOT NULL,
    -- Owning team; optional because PagerDuty services aren't always mapped to one of ours
    team_id              BIGINT REFERENCES team (id),
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_service_pagerduty_id UNIQUE (pagerduty_service_id)
);

INSERT INTO service (pagerduty_service_id, name)
SELECT service_id, max(coalesce(service_name, service_id))
FROM alert_event
WHERE service_id IS NOT NULL
GROUP BY service_id;

ALTER TABLE alert_event RENAME COLUMN service_id TO legacy_service_id;
ALTER TABLE alert_event ADD COLUMN service_id BIGINT REFERENCES service (id);

UPDATE alert_event a
SET service_id = s.id
FROM service s
WHERE s.pagerduty_service_id = a.legacy_service_id;

ALTER TABLE alert_event
    DROP COLUMN legacy_service_id,
    DROP COLUMN service_name;

CREATE INDEX ix_alert_event_service_id ON alert_event (service_id);

-- ---------------------------------------------------------------------------------------------------------
-- alert_event: richer data and enforced values
-- ---------------------------------------------------------------------------------------------------------
ALTER TABLE alert_event
    ADD COLUMN acknowledged_at TIMESTAMP(6),
    ADD COLUMN created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    ADD COLUMN updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    ALTER COLUMN status SET DEFAULT 'triggered',
    ALTER COLUMN status SET NOT NULL,
    ADD CONSTRAINT ck_alert_status CHECK (status IN ('triggered', 'acknowledged', 'resolved')),
    ADD CONSTRAINT ck_alert_severity CHECK (severity IN ('P1', 'P2', 'P3', 'P4', 'P5')),
    ADD CONSTRAINT ck_alert_urgency CHECK (urgency IN ('high', 'low')),
    ADD CONSTRAINT ck_alert_source CHECK (source IN ('API', 'API_SYNC', 'WEBHOOK', 'MANUAL')),
    ADD CONSTRAINT ck_alert_acknowledged_after_trigger
        CHECK (acknowledged_at IS NULL OR acknowledged_at >= triggered_at),
    ADD CONSTRAINT ck_alert_resolved_after_trigger
        CHECK (resolved_at IS NULL OR resolved_at >= triggered_at);

-- ---------------------------------------------------------------------------------------------------------
-- alert_assignment: who was paged, escalated to or reassigned, and when
-- ---------------------------------------------------------------------------------------------------------
CREATE TABLE alert_assignment (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id          BIGINT       NOT NULL REFERENCES alert_event (id) ON DELETE CASCADE,
    -- NULL when the PagerDuty user isn't one of our engineers (yet)
    engineer_id       BIGINT REFERENCES engineer_data (id),
    pagerduty_user_id VARCHAR(255),
    kind              VARCHAR(16)  NOT NULL,
    assigned_at       TIMESTAMP(6) NOT NULL,
    -- LOG: from the PagerDuty incident log (source of truth); WEBHOOK: provisional; BACKFILL: from V3;
    -- MANUAL: alerts created through the API
    source            VARCHAR(16)  NOT NULL,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_assignment_kind CHECK (kind IN ('PAGED', 'ESCALATED', 'REASSIGNED')),
    CONSTRAINT ck_assignment_source CHECK (source IN ('LOG', 'WEBHOOK', 'BACKFILL', 'MANUAL')),
    CONSTRAINT ck_assignment_who CHECK (engineer_id IS NOT NULL OR pagerduty_user_id IS NOT NULL),
    CONSTRAINT uq_assignment UNIQUE NULLS NOT DISTINCT (alert_id, kind, pagerduty_user_id, assigned_at)
);

CREATE INDEX ix_alert_assignment_alert_id ON alert_assignment (alert_id);
CREATE INDEX ix_alert_assignment_engineer ON alert_assignment (engineer_id, assigned_at);

-- Existing alerts: record who was paged, as already stored on the alert
INSERT INTO alert_assignment (alert_id, engineer_id, pagerduty_user_id, kind, assigned_at, source)
SELECT id, engineer_id, pager_duty_user_id, 'PAGED', triggered_at, 'BACKFILL'
FROM alert_event
WHERE engineer_id IS NOT NULL OR pager_duty_user_id IS NOT NULL;

-- ---------------------------------------------------------------------------------------------------------
-- oncall_shift: who was on call when (PagerDuty /oncalls)
-- ---------------------------------------------------------------------------------------------------------
CREATE TABLE oncall_shift (
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    engineer_id                    BIGINT       NOT NULL REFERENCES engineer_data (id) ON DELETE CASCADE,
    pagerduty_escalation_policy_id VARCHAR(255),
    pagerduty_schedule_id          VARCHAR(255),
    -- 1 = primary on call; higher levels are escalation backups
    escalation_level               SMALLINT     NOT NULL DEFAULT 1,
    starts_at                      TIMESTAMP(6) NOT NULL,
    ends_at                        TIMESTAMP(6) NOT NULL,
    created_at                     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at                     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_shift_period CHECK (ends_at > starts_at),
    CONSTRAINT ck_shift_level CHECK (escalation_level >= 1),
    CONSTRAINT uq_shift UNIQUE NULLS NOT DISTINCT
        (engineer_id, pagerduty_escalation_policy_id, escalation_level, starts_at)
);

CREATE INDEX ix_oncall_shift_engineer_period ON oncall_shift (engineer_id, starts_at, ends_at);
CREATE INDEX ix_oncall_shift_starts_at ON oncall_shift (starts_at);

-- ---------------------------------------------------------------------------------------------------------
-- updated_at triggers
-- ---------------------------------------------------------------------------------------------------------
CREATE TRIGGER trg_team_updated_at BEFORE UPDATE ON team
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_engineer_updated_at BEFORE UPDATE ON engineer_data
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_service_updated_at BEFORE UPDATE ON service
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_alert_event_updated_at BEFORE UPDATE ON alert_event
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_oncall_shift_updated_at BEFORE UPDATE ON oncall_shift
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------------------------------------
-- Scorer contract: existing views gain columns (appended), two new views
-- ---------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW scoring_alert_v AS
SELECT a.id                                                  AS alert_id,
       a.engineer_id,
       a.severity,
       a.status,
       a.triggered_at,
       a.resolved_at,
       a.acknowledged_at,
       (a.triggered_at AT TIME ZONE 'UTC') AT TIME ZONE t.timezone AS triggered_at_local,
       (SELECT count(*)
        FROM alert_assignment x
        WHERE x.alert_id = a.id AND x.kind = 'ESCALATED')    AS escalation_count
FROM alert_event a
         JOIN engineer_data e ON e.id = a.engineer_id
         JOIN team t ON t.id = e.team_id
WHERE a.engineer_id IS NOT NULL;

-- Escalations and reassignments to our engineers (the first page is already scoring_alert_v.engineer_id)
CREATE VIEW scoring_assignment_v AS
SELECT x.alert_id, x.engineer_id, x.kind, x.assigned_at
FROM alert_assignment x
WHERE x.engineer_id IS NOT NULL
  AND x.kind IN ('ESCALATED', 'REASSIGNED');

CREATE VIEW scoring_oncall_v AS
SELECT engineer_id, escalation_level, starts_at, ends_at
FROM oncall_shift;

COMMENT ON VIEW scoring_assignment_v IS 'Scorer read contract: escalations/reassignments. Timestamps are UTC.';
COMMENT ON VIEW scoring_oncall_v IS 'Scorer read contract: on-call shifts. Timestamps are UTC.';

-- If the least-privilege scorer role already exists (ops/sql/create_scorer_readonly_role.sql), extend it
DO
$$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fairness_scorer') THEN
        GRANT SELECT ON scoring_assignment_v, scoring_oncall_v TO fairness_scorer;
    END IF;
END
$$;
